### ISSUE TITLE
Worst commit messages ever.

### ISSUE THREAD

**Issue by lpil** [mjftw/individual_project#2]
:confused: 

```
* 85c7822 (HEAD, origin/master, origin/HEAD, master) updated project plan
* 83f0a82 'Commit_from_Code::Block_IDE'
* 3a0229e 'Commit_from_Code::Block_IDE'
* 2c5d616 'Commit_from_Code::Block_IDE'
* 4072933 'Commit_from_Code::Block_IDE'
* 689c025 'Commit_from_Code::Block_IDE'
* f40b22e active_shape_model slider program update
* 8f0d0e7 'Commit_from_Code::Block_IDE'
* 6128673 (grafted) 'Commit_from_Code::Block_IDE'
```

**Comment by mjftw** [comment]
I know I know, My git is a horrible mess.
The commits from codeblocks are just a script I added to the codeblocks
tools so that I could do quick commits.
Like I said, only me that uses this project, so it doesn't matter if it's a
mess.
I'm totally going to put the repo back on private to hide my mess if you
keep complaining :P

**Comment by lpil** [comment]
Gotta get out of those bad habits, man :P

**Comment by mjftw** [comment]
I promise I'll fix my habits for my next project :p
On Sun, Apr 05, 2015 at 2:05 PM, Louis Pilfold <notifications@github.com> wrote:Gotta get out of those bad habits, man :P
